Fix/python install
karaagro/cadi-ai pull request #35
Opened 2024-01-03 17:30 UTC by D-K-Asiedu

2024-01-03 18:43 UTC, atamino approved these changes

2024-01-03 18:44 UTC, ka-fuachie23 approved these changes

2024-01-03 22:14 UTC, atamino requested changes
pls change the base branch to dev

2024-01-04 16:50 UTC, atamino approved these changes

2024-01-04 17:11 UTC, merged